### ISSUE TITLE
Cannot compile - Missing SConscript 'godot_cpp/SConstruct'

### ISSUE THREAD

**Issue by solarstrings** [VoylinsGamedevJourney/gde_gozen#16]
### GoZen GDExtension version

Version 3.1

### Godot version

4.3

### System information

Ubuntu Linux 23.10

### Issue description

After running the build.py script, the following error occurs:

scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=False to SConscript calls.
Missing SConscript 'godot_cpp/SConstruct'
File "/home/studioputer/Godot/VideoPlayer/gde_gozen-master/SConstruct", line 7, in <module>
AttributeError: 'NoneType' object has no attribute 'Append':
  File "/home/studioputer/Godot/VideoPlayer/gde_gozen-master/SConstruct", line 8:
    env.Append(CPPPATH=['src'])

**Comment by voylin** [comment]
Sorry for the late reply, never received a notification about this. Did you initialize the submodules?
